/**
 * List AI Canvas resources and optionally filter them by canonical assetId.
 */

import { cli, Strategy } from '@jackwener/opencli/registry';

import {
  DEFAULT_CANVAS_EVENT_MAX_PAGES,
  normalizeCanvasResourceArgs,
} from './src/canvas-resource-contract.js';
import { JIMENG_DOMAIN } from './src/canvas-contract.js';
import { runJimengCanvasStatus } from './src/canvas-resource-dom.js';

export const canvasStatusCommand = cli({
  site: 'jimeng-agent',
  name: 'canvas-status',
  access: 'read',
  description: 'List all AI Canvas resources, or exactly correlate resources generated by one canvas-video assetId',
  domain: JIMENG_DOMAIN,
  strategy: Strategy.COOKIE,
  browser: true,
  siteSession: 'ephemeral',
  defaultWindowMode: 'foreground',
  navigateBefore: false,
  args: [
    {
      name: 'canvas',
      valueRequired: true,
      required: true,
      help: 'Existing canvas project id or full AI Canvas URL',
    },
    {
      name: 'asset_id',
      valueRequired: true,
      help: 'Optional 16-character assetId returned by canvas-video for exact turn/resource correlation',
    },
    {
      name: 'max_pages',
      type: 'int',
      default: DEFAULT_CANVAS_EVENT_MAX_PAGES,
      help: `Maximum pages to read per session/event list (default ${DEFAULT_CANVAS_EVENT_MAX_PAGES})`,
    },
  ],
  columns: [
    'status',
    'projectId',
    'projectTitle',
    'assetId',
    'sessionId',
    'turnId',
    'nodeId',
    'resourceId',
    'submitId',
    'type',
    'createdAt',
    'model',
    'ratio',
    'resolution',
    'duration',
    'creditsAmount',
    'url',
    'downloadUrl',
    'coverUrl',
    'errorCode',
    'errorMessage',
    'correlation',
    'resourceCount',
    'sessionsScanned',
    'eventsScanned',
    'scanComplete',
    'canvasUrl',
  ],
  validateArgs: (kwargs) => {
    normalizeCanvasResourceArgs(kwargs);
  },
  func: async (page, kwargs) => {
    const canonical = normalizeCanvasResourceArgs(kwargs);
    return runJimengCanvasStatus(page, canonical);
  },
});
